export const SUBMIT_FETCH_PERSON_BY_ID = 'SUBMIT_FETCH_PERSON_BY_ID';
export const SUBMIT_FETCH_TITLE_BY_ID = 'SUBMIT_FETCH_TITLE_BY_ID';
export const SUBMIT_PERSON_SEARCH = 'SUBMIT_PERSON_SEARCH';
export const SUBMIT_TITLE_SEARCH = 'SUBMIT_TITLE_SEARCH';
