export const SUBMIT_SEARCH = 'SUBMIT_SEARCH';
export const SUBMIT_SEARCH_PAGE = 'SUBMIT_SEARCH_PAGE';
export const GOT_SEARCH_RESULTS = 'GOT_SEARCH_RESULTS';
export const STARTED_HANDLE_SUBMIT_SEARCH_SAGA = 'STARTED_SEARCH_SAGA';
export const STARTED_HANDLE_SUBMIT_SEARCH_PAGE_SAGA = 'STARTED_HANDLE_SUBMIT_SEARCH_PAGE_SAGA';
export const GOT_SEARCH_ERROR = 'GOT_SEARCH_ERROR';
